services:
  mongo-g04a:
    image: mongo:8.0.32-noble@sha256:01354084d2ae665d2e79b79b0cdc50c2c0c98873618912d9a2c8c9cb5c3d24e6
    command:
      - mongod
      - --port
      - '27028'
      - --replSet
      - rs0
      - --bind_ip_all
    ports:
      - 127.0.0.1:27028:27028
    healthcheck:
      test:
        - CMD-SHELL
        - 'mongosh --quiet --port 27028 --eval "db.adminCommand({ ping: 1 }).ok === 1"'
      interval: 2s
      timeout: 3s
      retries: 30
