export {
  G04A_FACE_QUALIFICATION_INDEX,
  G04A_FACE_SLOTS_COLLECTION,
  G04A_FACE_SLOTS_INDEXES,
  G04A_FACE_SLOTS_VALIDATOR,
  G04A_FACE_SUBJECT_INDEX,
  ensureG04aFaceSlotsCollection,
  type G04aFaceSlotDocument,
} from './g04a-face-index-schema.js';
export {
  G04A_DEFAULT_DATABASE,
  G04A_MONGO_VERSION,
  G04aFaceIndexExperiment,
  G04aInjectedRollbackError,
  G04aTransactionError,
  G04aMongoTopologyError,
  G04aMongoVersionError,
  classifyG04aTransactionError,
  createG04aFaceIndexFixture,
  isMongoDuplicateKeyError,
  type G04aFaceBindingInput,
  type G04aFaceIndexFixture,
  type G04aFaceReplacementInput,
  type G04aParallelBindingInput,
  type G04aParallelSessionOutcome,
  type G04aTransactionErrorClassification,
  type G04aTransactionErrorKind,
  type G04aTransactionStage,
  type G04aWriterSessionRead,
} from './g04a-face-index-experiment.js';
