export {
  G04A_FACE_QUALIFICATION_INDEX,
  G04A_FACE_SLOTS_COLLECTION,
  G04A_FACE_SLOTS_INDEXES,
  G04A_FACE_SLOTS_VALIDATOR,
  G04A_FACE_SUBJECT_INDEX,
  ensureG04aFaceSlotsCollection,
  type G04aFaceSlotDocument,
} from './g04a-face-index-schema.js';
export {
  G04A_DEFAULT_DATABASE,
  G04A_MONGO_VERSION,
  G04aFaceIndexExperiment,
  G04aInjectedRollbackError,
  G04aTransactionError,
  G04aMongoTopologyError,
  G04aMongoVersionError,
  classifyG04aTransactionError,
  createG04aFaceIndexFixture,
  isMongoDuplicateKeyError,
  type G04aFaceBindingInput,
  type G04aFaceIndexFixture,
  type G04aFaceReplacementInput,
  type G04aParallelBindingInput,
  type G04aParallelSessionOutcome,
  type G04aTransactionErrorClassification,
  type G04aTransactionErrorKind,
  type G04aTransactionStage,
  type G04aWriterSessionRead,
} from './g04a-face-index-experiment.js';
export {
  G04B_EVENT_EXTERNAL_INDEX,
  G04B_EVENT_COMPARISON_INDEX,
  G04B_EVENT_INDEXES,
  G04B_EVENTS_COLLECTION,
  G04B_EVENTS_VALIDATOR,
  G04B_FACE_SLOTS_COLLECTION,
  G04B_METADATA_COLLECTION,
  G04B_METADATA_VALIDATOR,
  G04B_QUALIFICATION_INDEXES,
  G04B_QUALIFICATION_QR_INDEX,
  G04B_QUALIFICATIONS_COLLECTION,
  G04B_QUALIFICATIONS_VALIDATOR,
  G04B_REASON_CODES,
  G04B_SOURCE_ALIAS_INDEX,
  G04B_SOURCE_INDEXES,
  G04B_SOURCES_COLLECTION,
  G04B_SOURCES_VALIDATOR,
  G04B_STARTUP_VECTORS,
  G04B_USER_INDEXES,
  G04B_USER_USERNAME_INDEX,
  G04B_USERS_COLLECTION,
  G04B_USERS_VALIDATOR,
  assertG04bMetadataBootstrap,
  ensureG04bSchema,
  type G04bCollections,
  type G04bEventDocument,
  type G04bMetadataDocument,
  type G04bQualificationDocument,
  type G04bSourceDocument,
  type G04bStartupVectorDocument,
  type G04bUserDocument,
} from './g04b-schema.js';
export {
  createG04bFixture,
  type G04bFixture,
} from './g04b-fixture.js';
export {
  G04B_DEFAULT_DATABASE,
  G04B_MONGO_VERSION,
  G04B_TRANSACTION_OPTIONS,
  G04bMongoPersistenceAdapter,
  G04bTechnicalError,
  G04bTransactionError,
  classifyG04bTransactionError,
  type G04bClock,
  type G04bCanonicalSnapshot,
  type G04bErrorFacts,
  type G04bManagementResult,
  type G04bPersistenceStatus,
  type G04bRecognitionResult,
  type G04bTransactionErrorKind,
  type G04bTransactionStage,
} from './g04b-persistence-adapter.js';
