export {
  type AccessScopeContext,
  type AccessQueryPort,
  type FaceMappingSnapshot,
  type ManagementChangePlan,
  type ManagementChangeResult,
  type ManagementCreateResult,
  type ManagementPublicChangeResult,
  type ManagementQualificationSummary,
  type ManagementRevokeResult,
  type ManagementUpdateResult,
  type LegacyManagementChangeResult,
  type ManagementQualificationSnapshot,
  type ManagementDataPort,
  type QualificationSnapshot,
  type RecognitionDataPort,
  type RecognitionPersistenceResult,
  type RecognitionPersistenceCommittedResult,
  type RecognitionPersistenceConflictResult,
  type RecognitionPersistenceUnknownResult,
  type RecognitionPersistenceErrorFacts,
  type RecognitionResultPlan,
  type RedactedAccessEventProjection,
  type RedactedQualificationProjection,
  type ResolvedIdentitySnapshot,
  type SourceFacts,
  type SourceFactsPort,
} from './access-ports.js';
export {
  isComparisonArtifact,
  type ComparisonArtifact,
  type ComparisonArtifactIssuer,
} from './comparison-artifact.js';
export {
  type ManagementPersistenceEnvelope,
  type RecognitionPersistenceEnvelope,
} from './trusted-operation.js';
export {
  type QueryAfterKey,
  type EventQueryFilters,
  type EventQueryItem,
  type EventQueryInput,
  type QueryDataPort,
  type QueryDetailResult,
  type QueryPage,
  type QualificationQueryInput,
  type QualificationQueryItem,
  type QuerySnapshotEvent,
  type QuerySnapshotQualification,
} from './query-ports.js';
