export {
  type AccessScopeContext,
  type AccessQueryPort,
  type FaceMappingSnapshot,
  type ManagementChangePlan,
  type ManagementDataPort,
  type QualificationSnapshot,
  type RecognitionDataPort,
  type RecognitionResultPlan,
  type RedactedAccessEventProjection,
  type RedactedQualificationProjection,
  type ResolvedIdentitySnapshot,
  type SourceFacts,
  type SourceFactsPort,
} from './access-ports.js';
